name: Build and Commit Build Artifacts

on:
  push:
    branches:
      main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
name: Checkout code
    uses: actions/checkout@v2

    
name: Setup Node.js
    uses: actions/setup-node@v2
    with:
      node-version: 14

    
name: Install dependencies
    run: npm install 
  run: npm run build
name: Commit and Push Build Artifacts
run: |
  git config --global user.email "devt1525@gmail.com"
  git config --global user.name "GitHub Actions"
  git add dist
  git commit -m "Add build artifacts"
  git push
name: Create Zip Folder
run: |
  mkdir package_files
  cp -r LICENSE README.md dist jest.config.js package-lock.json package.json tsconfig.json package_files
  zip -r package_files.zip package_files
name: Commit and Push Zip Folder
run: |
  git config --local user.email "devt1525@gmail.com"
  git config --local user.name "GitHub Action"
  git add package_files.zip
  git commit -m "Add my_folder.zip"

        # Push the changes back to the repository
        git push

